const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('megahub', {
  onRetroLaunchIssue: (callback) => ipcRenderer.on('retro-launch-issue', (_ev, data) => callback(data)),
  onAutostartIssue: (callback) => ipcRenderer.on('autostart-issue', (_ev, data) => callback(data)),
  onGameSessionEnded: (callback) => ipcRenderer.on('game-session-ended', (_ev, data) => callback(data)),
  onFocusQuickSearch: (callback) => ipcRenderer.on('focus-quick-search', () => callback()),
  onGameSessionStarted: (callback) => ipcRenderer.on('game-session-started', (_ev, data) => callback(data)),
  scanGames: () => ipcRenderer.invoke('scan-games'),
  getCachedGames: () => ipcRenderer.invoke('get-cached-games'),
  getSteamPlaytimeMap: () => ipcRenderer.invoke('get-steam-playtime-map'),
  launchGame: (game) => ipcRenderer.invoke('launch-game', game),
  installGame: (game) => ipcRenderer.invoke('install-game', game),
  connectAccount: (platform) => ipcRenderer.invoke('connect-account', platform),
  getMeta: (game, force) => ipcRenderer.invoke('get-meta', game, force),
  getSpecs: () => ipcRenderer.invoke('get-specs'),
  analyzeGame: (game) => ipcRenderer.invoke('analyze-game', game),
  getInstallSize: (dir) => ipcRenderer.invoke('get-install-size', dir),
  sgdbHasKey: () => ipcRenderer.invoke('sgdb-has-key'),
  sgdbSetKey: (key) => ipcRenderer.invoke('sgdb-set-key', key),
  getCover: (game) => ipcRenderer.invoke('get-cover', game),
  getWikipediaCover: (title) => ipcRenderer.invoke('get-wikipedia-cover', title),
  getRetroCatalog: (repo) => ipcRenderer.invoke('get-retro-catalog', repo),
  getRetroCover: (args) => ipcRenderer.invoke('get-retro-cover', args),
  tgdbHasKey: () => ipcRenderer.invoke('tgdb-has-key'),
  tgdbSetKey: (key) => ipcRenderer.invoke('tgdb-set-key', key),
  getRetroGameInfo: (title) => ipcRenderer.invoke('get-retro-game-info', title),
  retroCreateFolders: (args) => ipcRenderer.invoke('retro-create-folders', args),
  retroOpenFolder: (folderPath) => ipcRenderer.invoke('retro-open-folder', folderPath),
  retroGetLocalRomCounts: (ids) => ipcRenderer.invoke('retro-get-local-rom-counts', ids),
  retroScanRoms: (args) => ipcRenderer.invoke('retro-scan-roms', args),
  retroGetDownloadInfo: (consoleId) => ipcRenderer.invoke('retro-get-download-info', consoleId),
  retroGetEmulatorStatus: (args) => ipcRenderer.invoke('retro-get-emulator-status', args),
  retroDownloadEmulator: (args) => ipcRenderer.invoke('retro-download-emulator', args),
  textureSearchGame: (title) => ipcRenderer.invoke('texture-search-game', title),
  textureListMods: (args) => ipcRenderer.invoke('texture-list-mods', args),
  textureGetDownloadInfo: (modId) => ipcRenderer.invoke('texture-get-download-info', modId),
  textureDownloadInstall: (args) => ipcRenderer.invoke('texture-download-install', args),
  textureCheckAvailability: (title) => ipcRenderer.invoke('texture-check-availability', title),
  retroOpenEmulator: (exePath) => ipcRenderer.invoke('retro-open-emulator', exePath),
  retroGetLocations: (consoleId) => ipcRenderer.invoke('retro-get-locations', consoleId),
  retroPickEmulatorFolder: (consoleId) => ipcRenderer.invoke('retro-pick-emulator-folder', consoleId),
  retroPickRomsFolder: (consoleId) => ipcRenderer.invoke('retro-pick-roms-folder', consoleId),
  retroClearEmulatorLocation: (consoleId) => ipcRenderer.invoke('retro-clear-emulator-location', consoleId),
  retroClearRomsLocation: (consoleId) => ipcRenderer.invoke('retro-clear-roms-location', consoleId),
  retroGetDefaultRoot: () => ipcRenderer.invoke('retro-get-default-root'),
  retroPickDefaultRoot: () => ipcRenderer.invoke('retro-pick-default-root'),
  retroResetDefaultRoot: () => ipcRenderer.invoke('retro-reset-default-root'),
  retroLaunchRom: (args) => ipcRenderer.invoke('retro-launch-rom', args),
  retroGetRetroArchStatus: (consoleId) => ipcRenderer.invoke('retro-get-retroarch-status', consoleId),
  retroOpenBiosFolder: (consoleId) => ipcRenderer.invoke('retro-open-bios-folder', consoleId),
  retroInstallCore: (consoleId) => ipcRenderer.invoke('retro-install-core', consoleId),
  retroInstallCoreSystemFiles: (consoleId) => ipcRenderer.invoke('retro-install-core-system-files', consoleId),
  retroOpenRetroArch: () => ipcRenderer.invoke('retro-open-retroarch'),
  retroApplyResolutionPreset: (args) => ipcRenderer.invoke('retro-apply-resolution-preset', args),
  retroGetSkins: () => ipcRenderer.invoke('retro-get-skins'),
  retroInstallSkin: (id) => ipcRenderer.invoke('retro-install-skin', id),
  retroRestoreSkinSlot: (id) => ipcRenderer.invoke('retro-restore-skin-slot', id),
  raHasAccount: () => ipcRenderer.invoke('ra-has-account'),
  raGetAccount: () => ipcRenderer.invoke('ra-get-account'),
  raSetAccount: (args) => ipcRenderer.invoke('ra-set-account', args),
  raGetSummary: () => ipcRenderer.invoke('ra-get-summary'),
  raGetCompletionProgress: () => ipcRenderer.invoke('ra-get-completion-progress'),
  raGetGameProgress: (gameId) => ipcRenderer.invoke('ra-get-game-progress', gameId),
  raGetHistory: () => ipcRenderer.invoke('ra-get-history'),
  raRefreshHistory: () => ipcRenderer.invoke('ra-refresh-history'),
  raGetCheevosStatus: () => ipcRenderer.invoke('ra-get-cheevos-status'),
  raEnableCheevos: () => ipcRenderer.invoke('ra-enable-cheevos'),
  mhAchGetProgress: (args) => ipcRenderer.invoke('mh-ach-get-progress', args),
  getProfileStats: (args) => ipcRenderer.invoke('get-profile-stats', args),
  xeniaGetAchievements: () => ipcRenderer.invoke('xenia-get-achievements'),
  rpcs3GetTrophies: () => ipcRenderer.invoke('rpcs3-get-trophies'),
  backupExport: (localStorageData) => ipcRenderer.invoke('backup-export', localStorageData),
  backupImport: () => ipcRenderer.invoke('backup-import'),
  openMultiplayerReadme: (key) => ipcRenderer.invoke('open-multiplayer-readme', key),
  winMinimize: () => ipcRenderer.invoke('win-minimize'),
  winMaximizeToggle: () => ipcRenderer.invoke('win-maximize-toggle'),
  winClose: () => ipcRenderer.invoke('win-close'),
  winIsMaximized: () => ipcRenderer.invoke('win-is-maximized'),
  onWindowMaximizedChange: (callback) => ipcRenderer.on('window-maximized-change', (_ev, isMaximized) => callback(isMaximized)),
  companionGetStatus: () => ipcRenderer.invoke('companion-get-status'),
  companionGetWeeklyActivity: () => ipcRenderer.invoke('companion-get-weekly-activity'),
  companionGetRecentlyPlayed: (limit) => ipcRenderer.invoke('companion-get-recently-played', limit),
  widgetEnterMode: () => ipcRenderer.invoke('win-enter-widget-mode'),
  widgetSetShape: (shape) => ipcRenderer.invoke('win-set-widget-shape', shape),
  widgetExitMode: () => ipcRenderer.invoke('win-exit-widget-mode'),
  widgetHoverEnter: () => ipcRenderer.invoke('win-widget-hover-enter'),
  widgetHoverLeave: () => ipcRenderer.invoke('win-widget-hover-leave'),
  widgetSetAutoHide: (enabled) => ipcRenderer.invoke('win-widget-set-autohide', enabled),
  onWidgetRetractChange: (callback) => ipcRenderer.on('widget-retract-change', (_ev, retracted, edge) => callback(retracted, edge)),
  dealsGetTop: (force) => ipcRenderer.invoke('deals-get-top', force),
  dealsGetRecommendation: (force) => ipcRenderer.invoke('deals-get-recommendation', force),
});
